// Loads catalog.json (generated by scripts/build-catalog.mjs) and exposes it both as the
// nested structure and as a flat list of selectable units.

import catalogData from '../catalog.json';
import type { Catalog, Unit } from './types';

export const catalog = catalogData as unknown as Catalog;

export function unitKey(standardId: string, kind: string, slug: string): string {
  return `${standardId}:${kind}:${slug}`;
}

/** Flatten the catalog into selectable units (rules + documents), in source order. */
export function flattenUnits(cat: Catalog): Unit[] {
  const units: Unit[] = [];
  for (const std of cat.standards) {
    for (const file of std.files) {
      for (const section of file.sections) {
        for (const rule of section.rules) {
          units.push({
            key: unitKey(std.id, 'rule', rule.id),
            kind: 'rule',
            standardId: std.id,
            standardTitle: std.title,
            filePath: file.path,
            fileTitle: file.title,
            section: section.title,
            id: rule.id,
            sid: rule.sid,
            status: rule.status,
            title: rule.title,
            bodyMarkdown: rule.bodyMarkdown,
            params: rule.params,
          });
        }
      }
    }
    for (const doc of std.documents) {
      units.push({
        key: unitKey(std.id, doc.kind, doc.id),
        kind: doc.kind,
        standardId: std.id,
        standardTitle: std.title,
        filePath: doc.path,
        fileTitle: doc.title,
        section: '',
        id: doc.id,
        sid: doc.sid,
        status: doc.status,
        title: doc.title,
        bodyMarkdown: doc.bodyMarkdown,
        params: doc.params ?? [],
      });
    }
  }
  return units;
}

export const units: Unit[] = flattenUnits(catalog);
export const unitByKey: Map<string, Unit> = new Map(units.map((u) => [u.key, u]));
